Capture broken test output

diff --git a/.github/workflows/test-integration.yml b/.github/workflows/test-integration.yml
--- a/.github/workflows/test-integration.yml
+++ b/.github/workflows/test-integration.yml
@@ -86,10 +86,9 @@ jobs:
       - name: Run test
         id: test
         run: |
-          OUTPUT=$(make test-integration) || FAILED=$?
-          echo ${FAILED}
+          OUTPUT=$(make test-integration || echo "::set-output name=failed::true")
           echo ${OUTPUT}
-          echo "::set-env name=OUTPUT::$OUTPUT"
+          echo "TEST_OUTPUT=$(echo $OUTPUT)" >> $GITHUB_ENV
           go tool cover -func=./integration.coverprofile | sed -e 's/.go:[0-9]*:\t/.go\t/g' | sed -e 's/\t\t*/\t/g'  > integration.txt
           DIFF=$(test -e integration-base.txt && (diff integration-base.txt integration.txt || exit 0) || cat integration.txt)
           echo "${DIFF}"
@@ -98,7 +97,6 @@ jobs:
           echo "${TOTAL}"
           echo "::set-output name=diff::$DIFF"
           echo "::set-output name=total::$TOTAL"
-          echo "::set-output name=failed::$FAILED"
 
       - name: Store base coverage
         if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
@@ -155,8 +153,8 @@ jobs:
           PUBLISH_DIR: allure-history
 
       - name: Check test result
-        if: ${{ steps.test.outputs.failed }} != 0
+        if: ${{ steps.test.outputs.failed }} == 'true'
         run: |
           echo "::error ::Test failed"
-          echo ${OUTPUT}
+          echo ${TEST_OUTPUT}
           exit 1
