Capture broken test output

diff --git a/.github/workflows/test-integration.yml b/.github/workflows/test-integration.yml
--- a/.github/workflows/test-integration.yml
+++ b/.github/workflows/test-integration.yml
@@ -82,7 +82,9 @@ jobs:
       - name: Test
         id: test
         run: |
-          make test-integration || echo "::set-output name=failed::true"
+          TEST=$(make test-integration) || FAILED=$?
+          echo ${FAILED}
+          echo ${TEST}
           go tool cover -func=./integration.coverprofile | sed -e 's/.go:[0-9]*:\t/.go\t/g' | sed -e 's/\t\t*/\t/g'  > integration.txt
           OUTPUT=$(test -e integration-base.txt && (diff integration-base.txt integration.txt || exit 0) || cat integration.txt)
           echo "${OUTPUT}"
@@ -149,5 +151,5 @@ jobs:
       - name: Check test result
         if: ${{ steps.test.outputs.failed }} == 'true'
         run: |
-          echo "::error ::Test failed"
+          echo "::error ::Test failed, please check Test step logs"
           exit 1
